version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - 80:80
      - 443:443
    command: gunicorn -b 0.0.0.0:80 -b 0.0.0.0:443 -w 2 main:app
