version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - 18000:18000
    command: gunicorn -b 0.0.0.0:18000 -w 2 main:app
