version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - 18000:18000
    command: python main.py
